//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationExamParcial.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cursos
    {
        [Display(Name = "ID del Curso")]
        public int Id { get; set; }

        [Display(Name = "Nombre del Curso")]
        public string Nombre_del_curso { get; set; }

        [Display(Name = "Nivel del Curso")]
        public string Nivel { get; set; }

        [Display(Name = "Nombre del Profesor")]
        public string Profesor { get; set; }

        // Se ha eliminado la propiedad Estudiantes ya que no es necesaria
    }

}

