//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationExamParcial.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Estudiantes
    {
        [Display(Name = "ID del Estudiante")]
        public int Id { get; set; }

        [Display(Name = "Nombre del Estudiante")]
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }

        [Display(Name = "Carrera del Estudiante")]
        public string Carrera { get; set; }

        [Display(Name = "Correo Electrónico")]
        [Required(ErrorMessage = "El correo electrónico es obligatorio")]
        [EmailAddress(ErrorMessage = "El formato del correo electrónico no es válido")]
        public string CorreoElectronico { get; set; }
    }
}

